In [13]:
import numpy as np

# 1. Create a 1D array from 1 to 15
array_1d = np.arange(1, 16)
print(array_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [12]:
# 2. Create a 2D array (3x4) filled with ones
array_2d = np.ones((3, 4))
print(array_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# 4. Check shape, type, and dimension
print("Shape:", array_1d.shape)
print("Type:", type(array_1d))
print("Dimension:", array_1d.ndim)
print("Shape:", array_2d.shape)
print("Type:", type(array_2d))
print("Dimension:", array_2d.ndim)
print("Shape:", identity_matrix.shape)
print("Type:", type(identity_matrix))
print("Dimension:", identity_matrix.ndim)


Shape: (15,)
Type: <class 'numpy.ndarray'>
Dimension: 1
Shape: (3, 4)
Type: <class 'numpy.ndarray'>
Dimension: 2
Shape: (3, 3)
Type: <class 'numpy.ndarray'>
Dimension: 2


In [10]:
# 5. Create a Python list and convert to NumPy array
python_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]

print(python_list)

numpy_array = np.array(python_list)

print(numpy_array)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]
[ 10  20  30  40  50  60  70  80  90 100 110 120]
